export const yutData = {
  // --- '도'로 시작하는 조합 ---
  "도도도": { title: "건위천 (Great Success)", description: "Everything goes your way today!", advice: "Your energy is at its peak. Go for it!" },
  "도도개": { title: "천택리 (Step by Step)", description: "A day for steady progress.", advice: "Focus on small details; they lead to big wins." },
  "도도걸": { title: "천화동인 (Good Company)", description: "Great things happen with friends.", advice: "Teamwork makes the dream work today." },
  "도도윷": { title: "천뢰무망 (Sincerity)", description: "Honesty is your superpower today.", advice: "Be your true self, and people will notice." },
  "도개도": { title: "천풍구 (New Encounters)", description: "A surprising new idea or person is coming.", advice: "Keep an open mind for new opportunities." },
  "도개개": { title: "천수송 (Patience)", description: "A time to listen more than talk.", advice: "Patience will bring you the best result soon." },
  "도개걸": { title: "천산돈 (Mindful Rest)", description: "A perfect time for a short break.", advice: "Take a deep breath and recharge your battery." },
  "도개윷": { title: "천지비 (Steady Growth)", description: "You are building a strong foundation.", advice: "Don't rush; you're growing at the right pace." },
  "도걸도": { title: "택천쾌 (Decisiveness)", description: "Clear your mind and make a choice.", advice: "Trust your intuition; it's very sharp today." },
  "도걸개": { title: "택택리 (Joyful Steps)", description: "Happiness is found in small things.", advice: "Treat yourself to something sweet today." },
  "도걸걸": { title: "택화혁 (Positive Change)", description: "A fresh start is waiting for you.", advice: "Try something new; a new hobby or a new route." },
  "도걸윷": { title: "택뢰수 (Going with the Flow)", description: "Everything is moving naturally.", advice: "Relax and enjoy the rhythm of the day." },
  "도윷도": { title: "화천대유 (Abundance)", description: "You have plenty of resources and talent.", advice: "Share your good energy with those around you." },
  "도윷개": { title: "화택규 (Unique Vision)", description: "Seeing things from a different angle.", advice: "Your unique perspective is your strength today." },
  "도윷걸": { title: "화화리 (Bright Light)", description: "Your talent is shining brightly.", advice: "Stand tall; it's your time to be noticed." },
  "도윷윷": { title: "화뢰서합 (Clarity)", description: "A problem will be solved clearly.", advice: "Focus on what's important, and the rest will follow." },

  // --- '개'로 시작하는 조합 ---
  "개도도": { title: "뇌천대장 (Great Power)", description: "Strong energy is surrounding you.", advice: "Use your strength to help others today." },
  "개도개": { title: "뇌택귀매 (Hopeful Heart)", description: "A wish is starting to take shape.", advice: "Keep dreaming; your efforts are paying off." },
  "개도걸": { title: "뇌화풍 (Fruitful Harvest)", description: "Your hard work is bringing results.", advice: "Celebrate your small wins today." },
  "개도윷": { title: "뇌뢰진 (Energetic Start)", description: "A day full of dynamic energy.", advice: "Stay active; movement brings more luck." },
  "개개도": { title: "풍천소축 (Gentle Breeze)", description: "Soft efforts bring great results.", advice: "A kind word will open many doors today." },
  "개개개": { title: "중지곤 (Inner Strength)", description: "A day for solid internal growth.", advice: "Focus on learning and personal reflection." },
  "개개걸": { title: "풍화가인 (Warm Harmony)", description: "Home and family bring you peace.", advice: "Call a loved one or spend time with friends." },
  "개개윷": { title: "풍뢰익 (Mutual Benefit)", description: "A win-win situation is coming.", advice: "Collaborate; two heads are better than one." },
  "개걸도": { title: "수천수 (Waiting for Rain)", description: "Preparation is almost complete.", advice: "Just a little more patience, and it's your turn." },
  "개걸개": { title: "수택절 (Balance)", description: "A perfect balance in your life.", advice: "Keep a steady pace; you're doing great." },
  "개걸걸": { title: "수화기제 (Completion)", description: "A task will be successfully finished.", advice: "Double-check your work for a perfect finish." },
  "개걸윷": { title: "수뢰둔 (New Beginnings)", description: "Like a sprout pushing through soil.", advice: "Be brave; small challenges make you stronger." },
  "개윷도": { title: "산천대축 (Accumulation)", description: "You are collecting great wisdom.", advice: "Write down your ideas; they are valuable." },
  "개윷개": { title: "산택손 (Giving is Receiving)", description: "Kindness returns to you twofold.", advice: "Help someone today; it will make your day." },
  "개윷걸": { title: "산화비 (Inner Beauty)", description: "Your character shines more than looks.", advice: "Authenticity is your best accessory today." },
  "개윷윷": { title: "산뢰이 (Mindful Speech)", description: "Kind words lead to great things.", advice: "Speak with love and encouragement today." },

  // --- '걸'로 시작하는 조합 ---
  "걸도도": { title: "지천태 (Peaceful Mind)", description: "A very calm and stable day.", advice: "Enjoy the peace and meditate for a moment." },
  "걸도개": { title: "지택임 (Bright Future)", description: "Great opportunities are approaching.", advice: "Be ready to say 'Yes' to new challenges." },
  "걸도걸": { title: "지화명이 (Protective Wisdom)", description: "Your wisdom protects you today.", advice: "Stay humble and learn from every situation." },
  "걸도윷": { title: "지뢰복 (Return of Joy)", description: "Good news from the past returns.", advice: "Reconnect with an old friend today." },
  "걸개도": { title: "천지비 (Strong Foundation)", description: "Building something that lasts.", advice: "Focus on quality over quantity today." },
  "걸개개": { title: "택지췌 (Gathering Spirits)", description: "People are drawn to your energy.", advice: "It's a great day for social gatherings." },
  "걸개걸": { title: "화지진 (Rising Sun)", description: "You are rising like the morning sun.", advice: "Don't be afraid to show your potential." },
  "걸개윷": { title: "뢰지예 (Excitement)", description: "Fun events are planned for you.", advice: "Let loose and enjoy the festival atmosphere!" },
  "걸걸도": { title: "풍지관 (Observation)", description: "You see things others might miss.", advice: "Pay attention to your surroundings today." },
  "걸걸개": { title: "수지비 (New Friendships)", description: "Finding someone who understands you.", advice: "Be open to meeting new people at the booth." },
  "걸걸걸": { title: "산지박 (Recharging Energy)", description: "A day to save your energy.", advice: "Relaxing at home is the best medicine today." },
  "걸걸윷": { title: "중지곤 (Deep Roots)", description: "Stability is your theme today.", advice: "Trust your path; your roots are deep." },
  "걸윷도": { title: "천산돈 (Strategic Pause)", description: "Thinking before acting brings luck.", advice: "Plan your next move with a clear mind." },
  "걸윷개": { title: "택산함 (Sincere Connection)", description: "Your heart connects with others.", advice: "Listen to your feelings; they are telling the truth." },
  "걸윷걸": { title: "화산려 (Adventurous Spirit)", description: "A day for a little adventure.", advice: "Try a new food or explore a new place." },
  "걸윷윷": { title: "뢰산소과 (Detail Oriented)", description: "Small things matter a lot today.", advice: "Take care of the little things first." },

  // --- '윷'으로 시작하는 조합 ---
  "윷도도": { title: "풍천소축 (Gentle Flow)", description: "Life is moving smoothly like air.", advice: "Stay flexible and adapt to the flow." },
  "윷도개": { title: "풍택중부 (True Trust)", description: "Trusting yourself is the key.", advice: "Believe in your decisions today." },
  "윷도걸": { title: "풍화가인 (Harmony at Home)", description: "Happiness starts from within.", advice: "Spread joy to your closest friends." },
  "윷도윷": { title: "중풍손 (Gentle Influence)", description: "Your kindness influences others.", advice: "Lead by example with a gentle heart." },
  "윷개도": { title: "수풍정 (Clear Spring)", description: "Fresh energy is welling up.", advice: "Share your creative ideas with the world." },
  "윷개개": { title: "산풍고 (Refreshing Change)", description: "Cleaning up old habits.", advice: "A great day to organize your room or desk." },
  "윷개걸": { title: "지풍승 (Rising High)", description: "You are stepping up to a new level.", advice: "Keep climbing; the view is getting better." },
  "윷개윷": { title: "뢰풍항 (Consistency)", description: "Steady habits bring success.", advice: "Keep up the good work; you're on the right track." },
  "윷걸도": { title: "천수송 (Peaceful Negotiation)", description: "Finding a middle ground.", advice: "Seek harmony in all your conversations." },
  "윷걸개": { title: "택수곤 (Resilience)", description: "You are stronger than you think.", advice: "Every challenge is making you much tougher." },
  "윷걸걸": { title: "화수미제 (Infinite Potential)", description: "The best is yet to come.", advice: "Stay curious; new wonders are waiting." },
  "윷걸윷": { title: "뢰수해 (Solution Found)", description: "A complicated problem gets easy.", advice: "Let go of worries; solutions are coming." },
  "윷윷도": { title: "천산돈 (Wise Choice)", description: "Knowing when to act is wisdom.", advice: "Choose your battles wisely today." },
  "윷윷개": { title: "택산함 (Shared Feelings)", description: "Empathy brings people together.", advice: "Give someone a warm compliment today." },
  "윷윷걸": { title: "화산려 (Traveler's Joy)", description: "Feeling free and adventurous.", advice: "Enjoy the freedom of being yourself." },
  "윷윷윷": { title: "중산간 (Quiet Peace)", description: "A moment of perfect silence.", advice: "Enjoy some 'me-time' to find your peace." }
};